POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "First blog",
  "author": "Mary S.",
  "url": "https://github.com/kolibri0509",
  "likes": 1000
}
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Second post",
  "author": "kolibri0509",
  "url": "https://github.com/kolibri0509",
  "likes": 100
}
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Dont likes",
  "author": "kolibri0509",
  "likes":"",
  "url": "https://github.com/kolibri0509"
}