POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "First blog",
  "author": "Mary S.",
  "url": "https://github.com/kolibri0509",
  "likes": 1000
}
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Second post",
  "author": "kolibri0509",
  "url": "https://github.com/kolibri0509",
  "likes": 100
}
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Dont likes",
  "author": "kolibri0509",
  "likes":"",
  "url": "https://github.com/kolibri0509"
}
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Dont likes",
  "author": "kolibri0509",
  "likes":"",
  "url": "https://github.com/kolibri0509"
}
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "author": "kolibri0509",
  "likes":"",
  "url": "https://github.com/kolibri0509"
}
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Dont likes",
  "author": "kolibri0509",
  "likes":""
}
###
POST http://localhost:3003/api/authors
content-type: application/json

{
  "username": "kolibri0509",
  "name": "kolibri0509",
  "password":"kolibri0509"
}
###
POST http://localhost:3003/api/authors
content-type: application/json

{
  "username": "Mary S.",
  "name": "Mariya Spiridonova",
  "password":"134484"
}
###
POST http://localhost:3003/api/authors
content-type: application/json

{
  "username": "Bobbi",
  "name": "Bob"
}
###
POST http://localhost:3003/api/authors
content-type: application/json

{
  "username": "kolibri0509",
  "name": "kolrabi",
  "password":"bert"
}
###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcnkgUy4iLCJpZCI6IjY1ZGVmNjU5NDdjZTNlZjM2M2ExNDdkZiIsImlhdCI6MTcwOTI4MTc5OX0.Ikk2sx3pJDdjTnZ7Yshd-VD1WQLuWk7M3JDygDEqSi4

{
  "title": "authorization by token",
  "author": "Mary S.",
  "url": "https://github.com/kolibri0509",
  "likes": 1
}
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "author and blog",
  "author": "kolibri0509",
  "url": "https://github.com/kolibri0509",
  "likes": 8
}
###
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "kolibri0509",
  "password": "kolibri0509"
}
###
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "Mary S.",
  "password": "134484"
}